name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env file
      run: |
        touch .env
        echo "LINEAR_WEBHOOK_SECRET=test" >> .env
        echo "WEBHOOK_PORT=3000" >> .env
        echo "CLAUDE_PATH=/bin/echo" >> .env
        echo "WORKSPACE_BASE_DIR=./tmp/workspaces" >> .env
        echo "PROMPT_TEMPLATE_PATH=./examples/prompt-template.txt" >> .env
        echo "ANTHROPIC_API_KEY=test" >> .env
    
    - name: Run tests
      run: npm test
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        fail_ci_if_error: false